using Content.Client.UserInterface.Controls;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Modsuit.Ui;
using Content.Shared.Modsuit.Components;

namespace Content.Client.Modsuit;

[GenerateTypedNameReferences]
public sealed partial class ModsuitMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action? EjectBatteryButtonPressed;
    public Action<EntityUid>? RemoveModuleButtonPressed;

    public float AccumulatedTime;
    private readonly List<EntityUid> _modules = new();

    public EntityUid Entity;

    public ModsuitMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        BorgSprite.SetEntity(entity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        AccumulatedTime += args.DeltaSeconds;
        BorgSprite.OverrideDirection = (Direction)((int)AccumulatedTime % 4 * 2);
    }

    public void UpdateState(ModsuitBuiState state)
    {
        EjectBatteryButton.Disabled = !state.HasBattery;
        ChargeBar.Value = state.ChargePercent;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int)MathF.Round(state.ChargePercent * 100)));

        UpdateModulePanel();
    }

    private void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out ModsuitComponent? comp))
            return;

        ModuleCounter.Text = Loc.GetString("borg-ui-module-counter",
            ("actual", comp.ModuleContainer.Count),
            ("max", comp.MaxModuleCount));

        if (comp.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in comp.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in comp.ModuleContainer.ContainedEntities)
        {
            var moduleComponent = _entity.GetComponent<BorgModuleComponent>(module);
            var control = new ModsuitModuleControl(module, _entity, !moduleComponent.DefaultModule);
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }
}
