using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Silicons.Borgs;
using Content.Shared.Silicons.Borgs.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Modsuit;

[GenerateTypedNameReferences]
public sealed partial class ModsuitMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action? BrainButtonPressed;
    public Action? EjectBatteryButtonPressed;
    public Action<string>? NameChanged;
    public Action<EntityUid>? RemoveModuleButtonPressed;

    public float AccumulatedTime;
    private readonly List<EntityUid> _modules = new();

    public EntityUid Entity;

    public ModsuitMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EjectBatteryButton.OnPressed += _ => EjectBatteryButtonPressed?.Invoke();
        BrainButton.OnPressed += _ => BrainButtonPressed?.Invoke();

        UpdateBrainButton();
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
        BorgSprite.SetEntity(entity);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        AccumulatedTime += args.DeltaSeconds;
        BorgSprite.OverrideDirection = (Direction)((int)AccumulatedTime % 4 * 2);
    }

    public void UpdateState(BorgBuiState state)
    {
        EjectBatteryButton.Disabled = !state.HasBattery;
        ChargeBar.Value = state.ChargePercent;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int)MathF.Round(state.ChargePercent * 100)));

        UpdateBrainButton();
        UpdateModulePanel();
    }

    private void UpdateBrainButton()
    {
        if (_entity.TryGetComponent(Entity, out BorgChassisComponent? chassis) && chassis.BrainEntity is { } brain)
        {
            BrainButton.Text = _entity.GetComponent<MetaDataComponent>(brain).EntityName;
            BrainView.Visible = true;
            BrainView.SetEntity(brain);
            BrainButton.Disabled = false;
            BrainButton.AddStyleClass(StyleBase.ButtonOpenLeft);
        }
        else
        {
            BrainButton.Text = Loc.GetString("borg-ui-no-brain");
            BrainButton.Disabled = true;
            BrainView.Visible = false;
            BrainButton.RemoveStyleClass(StyleBase.ButtonOpenLeft);
        }
    }

    private void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out BorgChassisComponent? chassis))
            return;

        ModuleCounter.Text = Loc.GetString("borg-ui-module-counter",
            ("actual", chassis.ModuleCount),
            ("max", chassis.MaxModules));

        if (chassis.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in chassis.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in chassis.ModuleContainer.ContainedEntities)
        {
            var moduleComponent = _entity.GetComponent<BorgModuleComponent>(module);
            var control = new ModsuitModuleControl(module, _entity, !moduleComponent.DefaultModule);
            control.RemoveButtonPressed += () =>
            {
                RemoveModuleButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }
}
